PoteShareApp（宿泊予約アプリ）
amaco1489/pote_share_app pull request #1
Opened 2022-12-17 19:31 UTC by amaco1489

お世話になっております。

 実装した機能としては、

- TOP画面（キーワード・エリア検索）
- deviseを使ったユーザー登録 / 変更 / ログイン機能・プロフィール詳細ページ
- 貸し出すルームの登録機能・詳細 / 一覧ページ
- 借りるルームの予約機能・確認 / 詳細(確定) / 一覧ページ

その他
- フラッシュメッセージ・バリデーション（日本語化）
- パーシャルによるナビゲーションバー
- bootstrapを使ったレスポンシブ対応・デザイン（プルダウンメニューなど）

です。

2点ほど迷ったことについて、お伺いできると幸いです。

1. bootstrapはどの程度取り入れたらよいのか

ボタンデザインやグリッドシステムを使いこなせたらとても便利だと感じましたが、例えばjustify-content-between等を使い出すと逆にhtmlファイルが見づらくなってしまいました。今回の課題のcss/htmlにおいてはごちゃごちゃし過ぎていてお恥ずかしい限りです。
bootstrapとcssとの使いわけ方はどのようにしたらよいのでしょうか？

2. @reservation.new をするページはreservations/newのページでするべきだったのか

- [ 実現したかったこと ]
- reservations/confirmアクション内において、バリデーションに掛かったらrenderで元のページ（rooms/showページ）に戻る。
- 且つ<%= render "shared/error", obj: @reservation %>でエラーメッセージの表示。

質問サイトもgoogleも私なりに色々調べて試してはみましたが、↓の一つしか情報が見つかりませんでした（フラッシュメッセージにて表示）。
やはりコントローラーが異なると、renderで戻ること（@reservation.errorsを引き渡すこと）は不可能のなでしょうか？
[https://qiita.com/vsanna/items/6648379aa2740ea978e5](url)

ご確認よろしくお願いいたします。

2022-12-18 09:25 UTC, TakuyaChida requested changes
課題のご提出ありがとうございます！
内容を確認いたしました！

PRの説明文にPRの詳細を記述できていますね。
また、特にレビューしてほしい点などが記載できており大変素晴らしいと思いました！

1.bootstrapはどの程度取り入れたらよいのか
->bootstrapで実装を行うという仕様が決定した場合、表示側のHTMLは全てbootstrapで踏襲するのが一般的です。
ですが、1部機能のみbootstrapで実装を行うことなども開発現場ではよくあります。
amaco様がおっしゃるように、formやボタンデザイン, グリッド機能で画面レスポンシブを実現のみの用途でbootstrapを使用し、その他については通常のHTML, CSS, JSで実装するでもまったく問題ないです。
今度の改修やメンテナンス性を考え、最低限上記のような規則性があれば良いと思います！
実際の開発現場では、ある程度実装方法は設計段階で確立されている場合がほとんどなので、今回の場合は個人開発のように、この表現はbootstrapで行うなどの規則性があればとくに問題ないと思いました。

@reservation.new をするページはreservations/newのページでするべきだったのか
[ 実現したかったこと ]
reservations/confirmアクション内において、バリデーションに掛かったらrenderで元のページ（rooms/showページ）に戻る。
且つ<%= render "shared/error", obj: @reservation %>でエラーメッセージの表示。

->以下のルーティングと認識しています。
reservations.
show 「予約済みルーム一覧」
new 「新規ルーム予約」
confirm　「予約内容確認」
create, update　「予約内容確認で確定した内容を保存」

> @reservation.new をするページはreservations/newのページでするべきだったのか
「新規ルーム予約」を行うページはreservations/newのコントローラ側で行うべきです。
reservations/confirm「予約内容確認」でバリデーションにかかったら、元のページ「reservations/new」のページで入力内容を保持しつつ画面をnewの画面に戻してあげるのが通常のCRUDの流れだと思いました。

こちらのコメントの内容では一方通行なので、このあたり詳しくは質問ボックスなどをご活用ください！
かなり重要な箇所だと思いますので、鮮明にしつつ進めていく方が良いと思います！


下記、レビュー内容ですが、動作確認中に「新規ルーム登録」時に思ったような動作にならなかったため、修正をお願いいたします！
「新規ルーム登録」ボタン押下時に、rooms/new.html.erbが表示できずにルーム登録ができませんでした。
お手数ですが、ご確認をお願いいたします！

2022-12-18 09:25 UTC, TakuyaChida commented on config/routes.rb
> +  get 'top/index'
localhost:3000でアクセスしたときの初期画面の設定ができていますね。
素晴らしいです！

2022-12-18 09:25 UTC, TakuyaChida commented on app/views/top/index.html.erb
> +</div>
新規ユーザの場合、こちらの画面から「登録」を行うべきだと思いますが、
他のHTMLの要素に邪魔されてボタンが押下できなくなってしまっていますね。
一旦別のrooms/area_search側からボタンが押下できたので、以降気を付けるようにしましょう！
![スクリーンショット 2022-12-18 17 52 51](https://user-images.githubusercontent.com/74874584/208289407-4a7d6a28-2b30-4579-a5ae-69932b5d191e.png)

2022-12-18 09:25 UTC, TakuyaChida commented on app/views/top/index.html.erb
> +</div>
登録後のメニューも被ってしまっているようですね。
![スクリーンショット 2022-12-18 17 54 39](https://user-images.githubusercontent.com/74874584/208289482-2bfbd6e6-6c15-4d3d-a69c-216e6e8d2395.png)

2022-12-18 09:25 UTC, TakuyaChida commented on app/views/top/index.html.erb
> +</div>
この辺りのスタイルの適用やユーザビリティを考えたデザインなどは今後経験を積みながら学習していくとよいでしょう！
以前学習した内容を活用する取り組みはとても良いと思います！

2022-12-18 09:25 UTC, TakuyaChida commented on app/views/rooms/new.html.erb
> +</div>
動作確認を行ったところ、「新規ルーム登録」ボタンからこちらのHTMLが表示されないようです。
![スクリーンショット 2022-12-18 18 01 52](https://user-images.githubusercontent.com/74874584/208289738-31efdf1c-f13c-4e19-b435-fee48949e93f.png)
rooms/newのURLにはなっているようです。
こちら正常に表示、新規に部屋登録ができるように修正をお願いいたします！

2022-12-18 09:25 UTC, TakuyaChida commented on .gitignore
> +/public/uploads/
アップロードファイルの差分除外ができていますね。
素晴らしいです！

2022-12-18 10:30 UTC, amaco1489 commented on app/views/top/index.html.erb
> +</div>
早速のレビューありがとうございます！

確認したところ、私の方ではトップページの表示も新規ルーム登録も正常に機能しているため、どこを修正すれば良いか分からず・・・
画像ご確認できますでしょうか？

<img width="1470" alt="スクリーンショット 2022-12-18 19 08 13" src="https://user-images.githubusercontent.com/116137741/208293279-fa68464e-4dc9-48f9-8927-0b2332aac6e3.png">

<img width="1470" alt="スクリーンショット 2022-12-18 19 09 11" src="https://user-images.githubusercontent.com/116137741/208293363-17f53b4f-a5cb-46ed-b80e-ad74f02eb55e.png">

2022-12-18 10:39 UTC, amaco1489 commented on app/views/rooms/new.html.erb
> +</div>
エラー時と登録後（登録済みルーム一覧へリダイレクト）のスクショです。
<img width="1470" alt="スクリーンショット 2022-12-18 19 36 24" src="https://user-images.githubusercontent.com/116137741/208293669-a09726e1-dd20-4f02-a647-75e01dfecbfb.png">
<img width="1470" alt="スクリーンショット 2022-12-18 19 34 31" src="https://user-images.githubusercontent.com/116137741/208293673-c5fd63b3-952c-4124-833d-817f9f666064.png">

2022-12-19 07:46 UTC, amaco1489 commented on app/views/top/index.html.erb
> +</div>
画像から判断するとbootstrapが一切適用されていなかったようなので、yarnにて bootstrap ・jquery・popper.jsの再インストールと、それに付随したconfig/webpack/environment.js等への追記をしました。

修正後、
- git clone https://github.com/amaco1489/pote_share_app.git　pote_share_confirm　（新規フォルダ？）
- git checkout -b develop
- git pull origin develop
- bundle install
- rails db:migrate
- rails webpacker:install
- rails s
で確認してみました。
（"自身"での確認方法として合っているのか分からないので、他の方法があればご教示いただけると幸いです）

むしろなぜ、上記の記載がないのに正常に表示されていたのか。
再インストール前はそもそもpackage.jsonにも追記されておらず、.gitignore管理下なのかとnode_modules内も探しましたが見当たりませんでした。

再度ご確認お願いいたします。

2022-12-19 09:03 UTC, YamanakaSayaka reviewed
確認しました。
機能は問題なさそうなのですが、全体的に画面が大きく崩れてしまっています。
<img width="657" alt="スクリーンショット 2022-12-19 17 47 16" src="https://user-images.githubusercontent.com/79829190/208387638-b6c10adf-516d-4335-8a4a-3300b304d9dc.png">

<img width="380" alt="スクリーンショット 2022-12-19 17 49 22" src="https://user-images.githubusercontent.com/79829190/208387627-59a6aa34-8955-4871-88f2-d8f4554c4202.png">
こちら修正して、再度ご提出をお願いします！
Railsの課題ではPRでのやり取りはレビュアーが毎回ランダムになる関係で返信ができないため、わからなければ一度質問ボックスに質問いただければと思います。

2022-12-19 09:03 UTC, YamanakaSayaka commented on app/controllers/reservations_controller.rb
> +    @reservations = current_user.reservations.all
絞り込みできていていいですね。

2022-12-19 09:03 UTC, YamanakaSayaka commented on app/models/reservation.rb
> +  validate :min_total_gests
バリデーションも細かくかけられていて素晴らしいです。

2022-12-19 09:03 UTC, YamanakaSayaka commented on app/views/layouts/application.html.erb
> +        <nav class="header-nav">
ヘッダーもパーシャル化できるといいですね。メンテナンスしやすくなると思います。

2022-12-20 02:29 UTC, YamanakaSayaka reviewed
LGTMです！
よくできていると思います。おつかれさまでした！

2022-12-23 07:44 UTC, amaco1489 commented on app/views/layouts/application.html.erb
> +        <nav class="header-nav">
確かにこのページが長々としてしまっても良いものかと感じておりました。
ありがとうございます！

2022-12-23 08:29 UTC, amaco1489 commented on app/views/top/index.html.erb
> +</div>
bootstrapのインストール方法から記述まで色々間違っていたようで、
一度目、二度目の提出でかなりお見苦しいものを出してしまい、お手間をお掛けしてしまい大変申し訳ありませんでした。

また、疑問点にご返信いただきありがとうございます。

>bootstrapで実装を行うという仕様が決定した場合、表示側のHTMLは全てbootstrapで踏襲するのが一般的です。
そうなんですね・・・！ということは、もしbootstrapを使いこなせたとしたら、必要最低限のデザイン・レイアウトはこれで事足りてしまうのですね。
bootstrapはまだまだ一部機能しか知らないので、今後はある程度の規則性を心掛けつつ、cssと使い分けて書いていこうと思います。

> new 「新規ルーム予約」
やはりそうですよね。
最初の段階ではroomの詳細ページにreservationのnewアクションをくっつける？とイメージしてたのですが、機能実装段階で手こずってしまい、、、今度書き直してみます！

レビューありがとうございました！

2023-01-07 13:41 UTC, merged